apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.server.deploymentAndServiceName }}
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
