apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.deploymentAndServiceName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.server.deploymentAndServiceName }}
  replicas: {{ .Values.server.replicas }}
  template:
      metadata:
        labels:
          app: {{ .Values.server.deploymentAndServiceName }}
      spec:
        imagePullSecrets:
          - name:  {{ .Values.defaultValues.imagePullSecretName }}
        containers:
          - name: {{ .Values.server.deploymentAndServiceName }}
            image: {{ .Values.server.dockerImage }}:{{ .Values.server.dockerTag }}
            imagePullPolicy: {{ .Values.defaultValues.imagePullPolicy }}
            env:
            - name: DB_HOST
              value: {{ .Values.server.dbHostname }}
            - name: SSL_FOR_DB
              value: {{ .Values.server.sslForDB }}
