apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.deploymentAndServiceName }}
spec:
  type: {{ .Values.server.serviceType }}
  selector:
    app: {{ .Values.server.deploymentAndServiceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.servicePort }}
      targetPort: {{ .Values.server.serviceTargetPort }}
