apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.deploymentAndServiceName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.deploymentAndServiceName }}
  replicas: {{ .Values.db.replicas }}
  template:
      metadata:
        labels:
          app: {{ .Values.db.deploymentAndServiceName }}
      spec:
        imagePullSecrets:
          - name:  {{ .Values.defaultValues.imagePullSecretName }}
        containers:
          - name: {{ .Values.db.deploymentAndServiceName }}
            image: {{ .Values.db.dockerImage }}:{{ .Values.db.dockerTag }}
            imagePullPolicy: {{ .Values.defaultValues.imagePullPolicy }}
            envFrom:
              - secretRef: 
                  name: {{ .Values.db.credentialsSecretName }}
                  optional: false
