{{- if .Values.db.dbInCluster }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.deploymentAndServiceName }}
spec:
  type: {{ .Values.db.serviceType }}
  selector:
    app: {{ .Values.db.deploymentAndServiceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.servicePort }}
      targetPort: {{ .Values.db.serviceTargetPort }}
{{- end }}