apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: zefirnikolov/privatization:aksweb-agic
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          volumeMounts:
            - name: cert-volume
              mountPath: "/etc/nginx/certs"
              readOnly: true
      imagePullSecrets:
        - name: my-registry-secret
      volumes:
        - name: cert-volume
          secret:
            secretName: ssl-cert-production
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web

  ports:
    - name: https
      port: 443
      targetPort: 443
  type: ClusterIP
