apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.deploymentAndServiceName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.web.deploymentAndServiceName }}
  replicas: {{ .Values.web.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.deploymentAndServiceName }}
    spec:
      imagePullSecrets:
      - name:  {{ .Values.defaultValues.imagePullSecretName }}
      containers:
      - name: {{ .Values.web.deploymentAndServiceName }}
        image: {{ .Values.web.dockerImage }}:{{ .Values.web.dockerTag }}
        imagePullPolicy: {{ .Values.defaultValues.imagePullPolicy }}
        volumeMounts:
        - name: noop-mount
          mountPath: "/long/place/holder/folder/noop"
          readOnly: true
        {{- if .Values.web.sslAtPod }}
        - name: tls-certs
          mountPath: "/etc/nginx/certs"
          readOnly: true
        {{- end }}
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
      volumes:
      - name: noop-mount
        emptyDir: {}
      {{- if .Values.web.sslAtPod }}
      - name: tls-certs
        secret:
          secretName: ssl-cert-production
      {{- end }}
