apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-routing
spec:
  ingressClassName: nginx
  {{- if .Values.web.ssl }}
  tls:
  - hosts:
    - zefirnikolov.com
    - www.zefirnikolov.com
    secretName: ssl-cert-production
   {{- end }}
  rules:
  - host: zefirnikolov.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.web.deploymentAndServiceName }}
            port:
              number: {{ .Values.web.serviceTargetPort }}
  - host: www.zefirnikolov.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.web.deploymentAndServiceName }}
            port:
              number: {{ .Values.web.serviceTargetPort }}
