apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-routing
  annotations:
    {{- if .Values.web.agic }}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "zefirnikolov.com"
    {{- end }}
spec:
  {{- if .Values.web.agic }}
  ingressClassName: azure-application-gateway
  {{- else }}
  ingressClassName: nginx
  {{- end }}
  {{- if .Values.web.ssl }}
  tls:
  - hosts:
    - zefirnikolov.com
    - www.zefirnikolov.com
    secretName: ssl-cert-production
   {{- end }}
  rules:
  - host: zefirnikolov.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.web.deploymentAndServiceName }}
            port:
              {{- if .Values.web.agic }}
              number: 8443
              {{- else }}
              number: {{ .Values.web.serviceTargetPortHTTP }}
              {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-routing-www
  annotations:
    {{- if .Values.web.agic }}
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "www.zefirnikolov.com"
    {{- end }}
spec:
  {{- if .Values.web.agic }}
  ingressClassName: azure-application-gateway
  {{- else }}
  ingressClassName: nginx
  {{- end }}
  {{- if .Values.web.ssl }}
  tls:
  - hosts:
    - zefirnikolov.com
    - www.zefirnikolov.com
    secretName: ssl-cert-production
   {{- end }}
  rules:
  - host: www.zefirnikolov.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.web.deploymentAndServiceName }}
            port:
              {{- if .Values.web.agic }}
              number: 8443
              {{- else }}
              number: {{ .Values.web.serviceTargetPortHTTP }}
              {{- end }}
