apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.deploymentAndServiceName }}
spec:
  type: {{ .Values.web.serviceType }}
  selector:
    app: {{ .Values.web.deploymentAndServiceName }}
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.web.servicePortHTTP }}
    targetPort: {{ .Values.web.serviceTargetPortHTTP }}
  {{- if .Values.web.sslAtPod }}
  - protocol: TCP
    name: https
    port: 8443
    targetPort: 8443
  {{- end }}
