FROM mariadb:lts
ADD ./db_setup.sql /docker-entrypoint-initdb.d/init.sql

# docker run -p 3306:3306 --name mariadb -e MYSQL_ROOT_PASSWORD='iggRt9/390$123' -e MYSQL_USER=cash100m -e MYSQL_PASSWORD='9TToo02345/55' -d mariadb:test

