FROM mcr.microsoft.com/mssql/server:2022-latest

WORKDIR /usr/src/app
COPY init.sql ./init.sql
COPY entrypoint.sh ./entrypoint.sh

USER root

RUN chown mssql:mssql /usr/src/app/entrypoint.sh \
 && chmod 0550 /usr/src/app/entrypoint.sh

USER mssql
EXPOSE 1433
CMD ["/bin/bash", "/usr/src/app/entrypoint.sh"]
