defaultValues:
  imagePullSecretName: my-registry-secret
  imagePullPolicy: Always


db:
  dbInCluster: false
  deploymentAndServiceName: mydb
  replicas: 1
  dockerImage: zefirnikolov/privatization
  dockerTag: aksdb1
  credentialsSecretName: mysql-pass
  serviceType: ClusterIP
  servicePort: 3306
  serviceTargetPort: 3306

server:
  deploymentAndServiceName: server
  replicas: 1
  dockerImage: zefirnikolov/privatization
  dockerTag: aksserver2
  serviceType: ClusterIP
  servicePort: 5000
  serviceTargetPort: 5000
  # examples:
  dbHostname: "unique8.mysql.database.azure.com"
  dbUserPassword: "9TToo02345/55"
  dbUser: "cash100m"

web:
  deploymentAndServiceName: web
  replicas: 2
  dockerImage: zefirnikolov/privatization
  dockerTag: aksweb4
  serviceType: ClusterIP
  servicePortHTTP: 8080
  serviceTargetPortHTTP: 8080
  ssl: true
  sslAtPod: false
  agic: false
